import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import { ToastProvider } from "@/provider/toaster-provider";

const font = Roboto({ 
  subsets: ["latin"], 
  weight: ["400", "700"]
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`min-w-screen max-w-screen bg-white ${font.className}` }>
        <ToastProvider />
          {children}
      </body>
    </html>
  );
}
